export default {
  SYSTEM_ID: 'dnd5e',
  SW_5E_ID: 'sw5e',
  DEFAULT_STATUS_EFFECT_NAMES: [
    'Blinded',
    'Charmed',
    'Concentrating',
    'Dead',
    'Deafened',
    'Exhaustion 1',
    'Exhaustion 2',
    'Exhaustion 3',
    'Exhaustion 4',
    'Exhaustion 5',
    'Frightened',
    'Grappled',
    'Incapacitated',
    'Invisible',
    'Paralyzed',
    'Petrified',
    'Poisoned',
    'Prone',
    'Restrained',
    'Stunned',
    'Unconscious',
    'Wounded',
  ],
};
