name: Send to Discord

on:
  release:
    types: [released]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: GitHub Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.16.2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: "DFreds Convenient Effects - Release"
          content: "<@&1200173776898371635> <@&1200173086708871238>"
          footer_timestamp: true
